networks:
  shanda-network:
    driver: bridge

services:
  # start a react-native server
  # app:
  #   container_name: shanda_frontend
  #   build:
  #     context: ./frontend
  #     args:
  #       - NODE_ENV=development
  #     dockerfile: app.Dockerfile
  #   environment:
  #     - NODE_ENV=development
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ./frontend:/app
  #     - ./frontend/app/node_modules:/app/node_modules
  #   networks:
  #     - shanda-network
  # start a nestjs server
  server:
    container_name: shanda_backend
    build:
      context: ./backend
      dockerfile: server.Dockerfile
    ports:
      - 4201:4201
    expose:
      - 4201
    volumes:
      - ./backend:/app
      - ./backend/app/node_modules:/app/node_modules
    networks:
      - shanda-network
  # start a postgresql db server
  # db:
  #   container_name: shanda_db
  #   build:
  #     context: ./data
  #     dockerfile: db.Dockerfile
  #   # image: arm64v8/mysql # add image in dockerfile
  #   environment:
  #   #   MYSQL_DATABASE: 'shanda'
  #     POSTGRES_USER: 'user'
  #     POSTGRES_PASSWORD: 'password'
  #   #   MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     - 5432:5432
  #   expose:
  #     - 5432
  #   restart: always
  #   volumes:
  #     - ./data/database/data:/var/lib/postgresql/data
  #   networks:
  #     - shanda-network
