networks:
  shanda-network:
    driver: bridge

services:
  app:
    container_name: shanda_frontend
    build:
      context: ./shanda-app
      args:
        - VITE_ENV=development
        - VITE_PORT=5173
        # - BUILDPLATFORM=linux/amd64
        # - BUILDPLATFORM=linux/arm64
        - BUILDPLATFORM=windows/amd64
      dockerfile: app.Dockerfile
    environment:
      - VITE_ENV=development
      - VITE_PORT=5173
    ports:
      - 5173:5173
    volumes:
      - ./shanda-app:/app
    networks:
      - shanda-network
  server:
    container_name: shanda_backend
    build:
      context: ./backend
      dockerfile: server.Dockerfile
      args:
        # - BUILDPLATFORM=linux/amd64
        # - BUILDPLATFORM=linux/arm64
        - BUILDPLATFORM=windows/amd64
    ports:
      - 4201:4201
      - 9229:9229
    expose:
      - 4201
    volumes:
      - ./backend:/app
    networks:
      - shanda-network
  db:
    container_name: shanda_db
    image: postgres
    environment:
      POSTGRES_USER: 'shanda'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'shanda'
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
      - ./data/scripts/init.sql:/docker-entrypoint-initdb.d/init-1.sql
      - ./data/scripts/insert.sql:/docker-entrypoint-initdb.d/init-2.sql
    networks:
      - shanda-network
