networks:
  shanda-network:
    driver: bridge

services:
  app:
    container_name: shanda_frontend
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
        - PORT=4200
      dockerfile: app.Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    networks:
      - shanda-network
  server:
    container_name: shanda_backend
    build:
      context: ./backend
      dockerfile: server.Dockerfile
    ports:
      - 4201:4201
    expose:
      - 4201
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    networks:
      - shanda-network
  db:
    container_name: shanda_db
    image: postgres
    environment:
      POSTGRES_USER: 'shanda'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'shanda'
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
    networks:
      - shanda-network
